CREATE TABLE `tb_userbaseinfo` (
  `UserSn` varchar(38) NOT NULL COMMENT '人员标识符',
  `UserName` varchar(30) DEFAULT NULL COMMENT '姓名',
  `UserNamePY` varchar(10) DEFAULT NULL COMMENT '名字对应拼音',
  `Sex` varchar(10) DEFAULT NULL COMMENT '性别',
  `Birthday` date DEFAULT NULL COMMENT '出生日期',
  `Nation` varchar(10) DEFAULT NULL COMMENT '民族',
  `OrganizationName` varchar(70) DEFAULT NULL COMMENT '单位名称',
  `OrganizationExtendInfo` varchar(20) DEFAULT NULL COMMENT '单位名称补充',
  `JobLevel` varchar(10) DEFAULT NULL COMMENT '职级',
  `JobName` varchar(50) DEFAULT NULL COMMENT '职务名称',
  `Family` varchar(10) DEFAULT NULL COMMENT '家庭出身',
  `Composition` varchar(10) DEFAULT NULL COMMENT '成分',
  ` PositionalTitles` varchar(50) DEFAULT NULL COMMENT '职称',
  `TakeOffice` date DEFAULT NULL COMMENT '任现职时间',
  `Health` varchar(10) DEFAULT NULL COMMENT '健康',
  `EducationalBackground` varchar(200) DEFAULT NULL COMMENT '学历',
  `School` varchar(10) DEFAULT NULL COMMENT '毕业学校',
  `EducationalLevel` varchar(10) DEFAULT NULL COMMENT '学历级别',
  `Degree` varchar(50) DEFAULT NULL COMMENT '学位',
  `Marital` varchar(10) DEFAULT NULL COMMENT '婚姻状况',
  `Major` varchar(30) DEFAULT NULL COMMENT '专业',
  `Worktime` int(11) DEFAULT NULL COMMENT '乡镇工作时间',
  `JoinJobTime` date DEFAULT NULL COMMENT '参加工作时间',
  `WorkTimeCorrect` int(11) DEFAULT NULL COMMENT '工龄计算矫正值',
  `PoliticsStatus` varchar(10) DEFAULT NULL COMMENT '政治面貌',
  `JoinOrgDate` date DEFAULT NULL COMMENT '参加组织日期',
  `PoliticsRemarkTag` varchar(10) DEFAULT NULL COMMENT '政治面貌注释标识',
  `Identity` varchar(10) DEFAULT NULL COMMENT '个人身份',
  `IdentityBeginDate` date DEFAULT NULL COMMENT '现身份起始日期',
  PRIMARY KEY (`UserSn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;